name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  forge-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: forge version
        run: forge --version
      - name: forge build
        run: forge build --sizes
      - name: forge test
        run: forge test -vvv
